steps:
# - name: gcr.io/$PROJECT_ID/cloudbuild-attestor
#   id: 'Check Vulnerability Scan results'
#   entrypoint: 'sh'
#   args:
#   - -xe
#   - -c
#   - |
#      /scripts/check_vulnerabilities.sh -p $PROJECT_ID -i gcr.io/$PROJECT_ID/gke-flask-app@sha256:${COMMIT_SHA} -t 5
# - name: 'gcr.io/$PROJECT_ID/cloudbuild-attestor'
#   id: 'Attest Vulnerability Scan'
#   entrypoint: 'sh'
#   args:
#   - -xe
#   - -c
#   - |-
#       FQ_DIGEST=$(gcloud container images describe --format 'value(image_summary.fully_qualified_digest)' gcr.io/$PROJECT_ID/gke-flask-app@sha256:${COMMIT_SHA})
#       /scripts/create_attestation.sh \
#         -p "$PROJECT_ID" \
#         -i "$${FQ_DIGEST}" \
#         -a "$_VULNZ_ATTESTOR" \
#         -v "$_VULNZ_KMS_KEY_VERSION" \
#         -k "$_VULNZ_KMS_KEY" \
#         -l "$_KMS_LOCATION" \
#         -r "$_KMS_KEYRING"

- id: gke-deploy-prod
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
    - 'run'
    - '-f'
    - './resources.yaml'
    - '--label=env-commit-sha=${SHORT_SHA}'
    - '--location=us-west1-b'
    - '--cluster=skaffold-prod'